Fix for exception when loading PE's with at least 1 empty section name
NationalSecurityAgency/ghidra pull request #2329
Opened 2020-10-02 17:50 UTC by ryanmkurtz

I came across some PE files where one of the section names was "".  When Ghidra tries to create a memory block for this section, it tries to give the block the name "", which results in an uncaught exception, preventing the PE from importing.  This just gives it a default name to allow the import to succeed.

2020-10-03 22:05 UTC, astrelsky commented
What happens if there is more than one without a name? I know elf segments will have a suffix appended to them.

2020-10-05 11:47 UTC, ryanmkurtz commented
Currently this will just keep calling them all <empty>

2020-10-05 12:12 UTC, ryanmkurtz commented
I also expected this to automatically append a suffix to the duplicate names since that is done in `MemoryBlockUtils`, so I debugged it a little.  It looks like since change 7385544bed227bac20ee6aee1b4f74fd4268900f by @ghidra1 , the suffix will only be applied to duplicate block names if they are overlays.

2020-10-07 01:51 UTC, astrelsky commented
Won't that cause a DuplicateNameException somewhere?

2020-10-07 11:59 UTC, ryanmkurtz commented
No, with the change I mentioned above, a DuplicateNameException is now only thrown when the memory blocks with the same name are overlays.

2020-10-09 20:52 UTC, dragonmacher requested changes

2020-10-13 17:40 UTC, dragonmacher approved these changes

2020-10-13 18:38 UTC, ghidra1 commented
Merged for 9.2

2020-10-13 18:38 UTC, closed without merging