Delay load import features
NationalSecurityAgency/ghidra pull request #2623
Opened 2021-01-05 16:03 UTC by tnrn9b

2021-01-06 13:51 UTC, ryanmkurtz commented
I haven't looked at the code yet, but my initial test for functionality looks good with the following simple program I wrote:

```
#include <Windows.h>

int main() {
	POINT p;
	wchar_t name[100];
	DWORD size = 100;

	CreateCursor(0, 1, 2, 3, 4, NULL, NULL); // user32.dll
	GetCursorPos(&p); // user32.dll
	GetUserName(name, &size); //advapi32.dll
}
```
The program was linked with the following flags to enable delay load importing:
`
/DELAYLOAD:"user32.dll" /DELAYLOAD:"advapi32.dll"`

Program can be downloaded here: [DelayLoadImport.zip](https://github.com/NationalSecurityAgency/ghidra/files/5776117/DelayLoadImport.zip)

Before:
<img width="658" alt="before" src="https://user-images.githubusercontent.com/5378554/103775417-050ca600-4ffc-11eb-965b-52abd9625c06.PNG">

After:
<img width="601" alt="after" src="https://user-images.githubusercontent.com/5378554/103775434-0a69f080-4ffc-11eb-8eb5-849dc56b509e.PNG">

2021-01-06 14:20 UTC, ryanmkurtz requested changes

2021-01-06 14:23 UTC, ryanmkurtz commented
I added a delayed import call into winsock which imports by ordinal, and got the following exception:

```
ERROR Error Importing File: Error importing file: DelayLoadImport.exe java.lang.NullPointerException
	at ghidra.app.util.opinion.PeLoader.processDelayImports(PeLoader.java:531)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:146)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$0(TaskRunner.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
  (ImporterUtilities.java:413) 
```

```
int main() {
	POINT p;
	wchar_t name[100];
	DWORD size = 100;

	CreateCursor(0, 1, 2, 3, 4, NULL, NULL); // user32.dll
	GetCursorPos(&p); // user32.dll
	GetUserName(name, &size); //advapi32.dll

	WSAGetLastError(); // Ws2_32.dll (import by ordinal)
}
```

[DelayLoadImportWinsock.zip](https://github.com/NationalSecurityAgency/ghidra/files/5776275/DelayLoadImportWinsock.zip)

2021-01-06 16:25 UTC, mumbel commented on Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/DelayImportDataDirectory.java
> +		} catch (DuplicateNameException | InvalidInputException e) {}
Any chance of you describing that in more detail, I didn't know this was an option

2021-01-06 22:13 UTC, tnrn9b commented on Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/DelayImportDataDirectory.java
> +		} catch (DuplicateNameException | InvalidInputException e) {}
Import the eclipse code preferences for the Ghidra project and apply the formmater

2021-01-07 04:15 UTC, tnrn9b commented
Reformatted and added structures for the delayed import by ordinal. Resolving the rest should be left to the end user or a script to be run post load.

2021-02-12 13:48 UTC, ryanmkurtz commented
I did some work on this and it's in internal review.  I was able to simplify it quite a bit because to get ordinals to work, you just have to name the external references "Ordinal_n", and something that comes later in the load process will go out and replace that with the real function name.

2021-02-18 16:53 UTC, closed without merging