SuperH: simplify div1 logic
NationalSecurityAgency/ghidra pull request #2864
Opened 2021-03-25 06:40 UTC by VGKintsugi

asdf-prime's modifications to div1 instruction. I don't have the skill to verify this is correct. See PR: #2478

2021-04-19 19:45 UTC, ghidra1 requested changes

2021-04-19 19:45 UTC, ghidra1 commented on Ghidra/Processors/SuperH/data/languages/superh.sinc
> +    $(Q_FLAG) = (m_eq_q * tmp1) + (!m_eq_q & (tmp1 == 0));
Re: `$(Q_FLAG) = (m_eq_q * tmp1) + (!m_eq_q & (tmp1 == 0));`
  Use * not &

2021-04-19 19:45 UTC, ghidra1 commented on Ghidra/Processors/SuperH/data/languages/superh.sinc
> +    local old_q_eq_m:1;
Not sure why local vars are pre-declared (although this had previously been done this way).  I generally find declaration on first write to be easier to read. (OPTIONAL)

2021-04-21 06:03 UTC, VGKintsugi commented
The choosery pattern change has been implemented. I skipped the optional change for fear of breaking things. I think this PR should be handled at the same time: https://github.com/NationalSecurityAgency/ghidra/pull/2863 because I mixed up the delay slots fix with this PR as well.

2021-05-24 03:18 UTC, VGKintsugi commented
@ryanmkurtz @ghidra1, @GhidorahRex,

Something with this merge isn't making sense to me. I'm not seeing any changes to the div1 instruction? The referenced commit (https://github.com/NationalSecurityAgency/ghidra/commit/e21149816cc4469b2f824bbba74692431456c486) appears to include the fixes for the delay slot instructions, but not the changes to div1. I'm assuming this is an error?

2021-05-24 13:49 UTC, ryanmkurtz commented
Yes, something went wrong on our end.   We are looking into it.

2021-06-07 03:08 UTC, VGKintsugi commented
@ryanmkurtz, 

I realize you guys are busy but can we try to get this PR into Ghidra 10.0? As is the Ghidra 10.0 Beta release notes (https://ghidra-sre.org/releaseNotes_10.0beta.html) are incorrect:  "Processors. Simplified SuperH div1 instruction. (GP-753, Issue #2864)". 

So we can update the release notes or get this PR out. Let me know if there's anything I can do to expedite the process. Thanks.

2021-06-07 11:33 UTC, ryanmkurtz commented
We left in the release note because we planned on getting it in for 10.0-final.  I temporarily removed the 10.0 milestone because it's still in internal review.  If it doesn't make it in for whatever reason, we plan on removing the release note.

2021-06-10 03:20 UTC, closed without merging

2021-06-10 03:41 UTC, ghidra1 commented
Change has been merged