Implement readlink -f equivalent in python
NationalSecurityAgency/ghidra pull request #4116
Opened 2022-03-31 10:49 UTC by mgrela

2022-03-31 17:25 UTC, ryanmkurtz commented
Do you know how far back macOS/OS X comes with python out of the box?  Is it easily uninstallable?

2022-04-02 18:33 UTC, mgrela commented
According to info in the Python docs python2.7 is shipped since osx 10.8 (https://docs.python.org/3/using/mac.html) so this is ages ago. 

As far as uninstalling it I don't think it's possible as it's part of the base system.

2022-04-07 07:21 UTC, ryanmkurtz requested changes

2022-04-07 07:21 UTC, ryanmkurtz commented on Ghidra/RuntimeScripts/Linux/ghidraRun
> +SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || python -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$0" 2>/dev/null || echo "$0")"
I actually don't have `python` on my Monterey Macbook, just `python3`.

2022-04-07 07:27 UTC, ryanmkurtz commented on Ghidra/RuntimeScripts/Linux/ghidraRun
> +SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || python -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$0" 2>/dev/null || echo "$0")"
I suppose [this is why](https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/), I'm running macOS 12.3.  I have XCode installed which would explain why I have python3 available to me.  But, it looks like starting with 12.3, we can't count on python being installed by default.

2022-04-07 07:29 UTC, closed without merging