eBPF processor support
NationalSecurityAgency/ghidra pull request #4378
Opened 2022-06-27 11:42 UTC by Nalen98

This merge request was made to add support for eBPF processor in Ghidra because of its growing popularity.

eBPF is a virtual machine in the Linux kernel that allows you to load arbitrary custom code that can be used for process tracing and packet filtering in the kernel space. The architecture is a RISC register machine with 11 64-bit registers, a software counter, and a 512-byte stack.

In 2019 I've implemented the Ghidra extension [eBPF Processor for Ghidra](https://github.com/Nalen98/eBPF-for-Ghidra) with support of amazing people ([@saruman9](https://github.com/saruman9), [@edigaryev](https://github.com/edigaryev), [@emteere](https://www.github.com/emteere)) and think that the moment has come when this project is ready to become part of Ghidra and work out of the box for all users and with no need to install the particular extension.

During this time, the following improvements were made regarding disassembly and decompilation of eBPF programs:
* eBPF maps implementation with custom relocation handler
* eBPF call-helpers as complete syscalls have their own signatures
* nice analysis bookmarks were provided
* added support for relative calls (R_BPF_64_32 relocation type)

2022-12-09 17:30 UTC, GhidorahRex requested changes
I think this is almost ready for us to accept. I found a couple minor issues, and suggested some enhancements to the processor module.

2022-12-18 20:20 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +#BPF_ALU
Issue "Add ALU32 support" fixed starting from here

2022-12-18 20:21 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +:MOV dst, src  is src & dst & op_alu_jmp_opcode=0xb & op_alu_jmp_source=1 & op_insn_class=0x7 { dst=src; }
I mark it as Issue "Add ALU32 support".

Fixed in https://github.com/NationalSecurityAgency/ghidra/pull/4378/commits/7035245efb0ee89801e8058ce4d3bbb5328b963e

Check out scrolling down a bit:
https://github.com/NationalSecurityAgency/ghidra/pull/4378/files#r1051659471

2022-12-18 20:22 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +:JA joff  is joff & op_alu_jmp_opcode=0x0 & op_alu_jmp_source=0 & op_insn_class=0x5 {
Fixed.

2022-12-18 20:25 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +:JSET dst, imm, joff  is imm & joff & dst & op_alu_jmp_opcode=0x4 & op_alu_jmp_source=0 & op_insn_class=0x5 {
Now it looks like:

```
:JSET dst, src, joff  is joff & src & dst & op_alu_jmp_opcode=0x4 & op_alu_jmp_source=1 & op_insn_class=0x5 {     
    if ((dst & src) != 0) goto joff;
}
```

2022-12-18 20:28 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +    if ((dst & imm) != 0) goto joff;
Fixed the issue described at https://github.com/NationalSecurityAgency/ghidra/pull/4378#discussion_r1043482967

2022-12-18 20:31 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +# BPF_ATOMIC
Added support for bpf_atomic instructions, https://github.com/NationalSecurityAgency/ghidra/pull/4378#discussion_r1043504826, according to the `imm` value

2022-12-18 20:33 UTC, Nalen98 commented on Ghidra/Processors/eBPF/data/languages/eBPF.sinc
> +:XADDStSrc dst, src  is src & dst & op_ld_st_mode=0x6 & op_ld_st_size=0x3 & op_insn_class=0x3 { *:8 dst=*:8 dst + src; }
Thanks for the materials.

https://github.com/NationalSecurityAgency/ghidra/pull/4378#discussion_r1051660744 refers to the line of code where the fix starts.

2022-12-19 08:31 UTC, jobermayr commented
"Fixing issues" introduces build errors:
`> Task :eBPF:sleighCompile FAILED`
Compiling ./data/languages/eBPF.slaspec:
eBPF.sinc:81: Size restriction error in table 'instruction' in constructor at eBPF.sinc:81
  Problem with 'dst' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:82: Size restriction error in table 'instruction' in constructor at eBPF.sinc:82
  Problem with 'dst' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:84: Size restriction error in table 'instruction' in constructor at eBPF.sinc:84
  Problem with 'dst' in 'Addition(+)' operator
  The output and all input sizes must match
eBPF.sinc:85: Size restriction error in table 'instruction' in constructor at eBPF.sinc:85
  Problem with 'dst' in 'Addition(+)' operator
  The output and all input sizes must match
eBPF.sinc:87: Size restriction error in table 'instruction' in constructor at eBPF.sinc:87
  Problem with 'dst' in 'Subtraction(-)' operator
  The output and all input sizes must match
eBPF.sinc:88: Size restriction error in table 'instruction' in constructor at eBPF.sinc:88
  Problem with 'dst' in 'Subtraction(-)' operator
  The output and all input sizes must match
eBPF.sinc:90: Size restriction error in table 'instruction' in constructor at eBPF.sinc:90
  Problem with 'dst' in 'Multiplication(*)' operator
  The output and all input sizes must match
eBPF.sinc:91: Size restriction error in table 'instruction' in constructor at eBPF.sinc:91
  Problem with 'dst' in 'Multiplication(*)' operator
  The output and all input sizes must match
eBPF.sinc:93: Size restriction error in table 'instruction' in constructor at eBPF.sinc:93
  Problem with 'dst' in 'Division(/)' operator
  The output and all input sizes must match
eBPF.sinc:94: Size restriction error in table 'instruction' in constructor at eBPF.sinc:94
  Problem with 'dst' in 'Division(/)' operator
  The output and all input sizes must match
eBPF.sinc:96: Size restriction error in table 'instruction' in constructor at eBPF.sinc:96
  Problem with 'dst' in 'Or(|)' operator
  The output and all input sizes must match
eBPF.sinc:97: Size restriction error in table 'instruction' in constructor at eBPF.sinc:97
  Problem with 'dst' in 'Or(|)' operator
  The output and all input sizes must match
eBPF.sinc:99: Size restriction error in table 'instruction' in constructor at eBPF.sinc:99
  Problem with 'dst' in 'And(&)' operator
  The output and all input sizes must match
eBPF.sinc:100: Size restriction error in table 'instruction' in constructor at eBPF.sinc:100
  Problem with 'dst' in 'And(&)' operator
  The output and all input sizes must match
eBPF.sinc:102: Size restriction error in table 'instruction' in constructor at eBPF.sinc:102
  Problem with 'dst' in 'Left shift(<<)' operator
  Output and first input must be the same size
eBPF.sinc:103: Size restriction error in table 'instruction' in constructor at eBPF.sinc:103
  Problem with 'dst' in 'Left shift(<<)' operator
  Output and first input must be the same size
eBPF.sinc:105: Size restriction error in table 'instruction' in constructor at eBPF.sinc:105
  Problem with 'dst' in 'Right shift(>>)' operator
  Output and first input must be the same size
eBPF.sinc:106: Size restriction error in table 'instruction' in constructor at eBPF.sinc:106
  Problem with 'dst' in 'Right shift(>>)' operator
  Output and first input must be the same size
eBPF.sinc:108: Size restriction error in table 'instruction' in constructor at eBPF.sinc:108
  Problem with 'dst' in 'Twos complement(-)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:110: Size restriction error in table 'instruction' in constructor at eBPF.sinc:110
  Problem with 'dst' in 'Remainder(%)' operator
  The output and all input sizes must match
eBPF.sinc:111: Size restriction error in table 'instruction' in constructor at eBPF.sinc:111
  Problem with 'dst' in 'Remainder(%)' operator
  The output and all input sizes must match
eBPF.sinc:113: Size restriction error in table 'instruction' in constructor at eBPF.sinc:113
  Problem with 'dst' in 'Exclusive or(^)' operator
  The output and all input sizes must match
eBPF.sinc:114: Size restriction error in table 'instruction' in constructor at eBPF.sinc:114
  Problem with 'dst' in 'Exclusive or(^)' operator
  The output and all input sizes must match
eBPF.sinc:116: Size restriction error in table 'instruction' in constructor at eBPF.sinc:116
  Problem with 'dst' in 'Signed right shift(s>>)' operator
  Output and first input must be the same size
eBPF.sinc:117: Size restriction error in table 'instruction' in constructor at eBPF.sinc:117
  Problem with 'dst' in 'Signed right shift(s>>)' operator
  Output and first input must be the same size
eBPF.sinc:211: Size restriction error in table 'instruction' in constructor at eBPF.sinc:211
  Problem with 'src' in 'Addition(+)' operator
  The output and all input sizes must match
eBPF.sinc:218: Size restriction error in table 'instruction' in constructor at eBPF.sinc:218
  Problem with 'src' in 'Or(|)' operator
  The output and all input sizes must match
eBPF.sinc:224: Size restriction error in table 'instruction' in constructor at eBPF.sinc:224
  Problem with 'src' in 'And(&)' operator
  The output and all input sizes must match
eBPF.sinc:230: Size restriction error in table 'instruction' in constructor at eBPF.sinc:230
  Problem with 'src' in 'Exclusive or(^)' operator
  The output and all input sizes must match
eBPF.sinc:238: Size restriction error in table 'instruction' in constructor at eBPF.sinc:236
  Problem with 'src' in 'Addition(+)' operator
  The output and all input sizes must match
eBPF.sinc:239: Size restriction error in table 'instruction' in constructor at eBPF.sinc:236
  Problem with 'src' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:252: Size restriction error in table 'instruction' in constructor at eBPF.sinc:250
  Problem with 'src' in 'Or(|)' operator
  The output and all input sizes must match
eBPF.sinc:253: Size restriction error in table 'instruction' in constructor at eBPF.sinc:250
  Problem with 'src' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:266: Size restriction error in table 'instruction' in constructor at eBPF.sinc:264
  Problem with 'src' in 'And(&)' operator
  The output and all input sizes must match
eBPF.sinc:267: Size restriction error in table 'instruction' in constructor at eBPF.sinc:264
  Problem with 'src' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:280: Size restriction error in table 'instruction' in constructor at eBPF.sinc:278
  Problem with 'src' in 'Exclusive or(^)' operator
  The output and all input sizes must match
eBPF.sinc:281: Size restriction error in table 'instruction' in constructor at eBPF.sinc:278
  Problem with 'src' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:295: Size restriction error in table 'instruction' in constructor at eBPF.sinc:292
  Problem with 'src' in 'Copy(=)' operator
  Input and output sizes must match; {type=real value_real=0x4 spaceid=null} != {type=handle value_real=0x0 spaceid=null}
eBPF.sinc:308: Size restriction error in table 'instruction' in constructor at eBPF.sinc:306
  Problem in 'Equality(==)' operator
  Inputs must be the same size
eBPF.sinc:309: Size restriction error in table 'instruction' in constructor at eBPF.sinc:306
  Problem i [...]

2022-12-19 10:06 UTC, Nalen98 commented
I figured out the problem, need to work on it a bit. Seems that as it was declared in 
https://docs.kernel.org/bpf/instruction-set.html#arithmetic-and-jump-instructions

```
BPF_ADD | BPF_X | BPF_ALU means:

dst_reg = (u32) dst_reg + (u32) src_reg;
```
Since the right side will be 32-bit, need to expand the result how it's done in x86:
```
MOVSXD op64, op32
```

2022-12-19 12:10 UTC, Nalen98 commented
After https://github.com/NationalSecurityAgency/ghidra/pull/4378/commits/9294580e8eaac61863f2f271c7b5e71ad77740c6:
```
> Task :eBPF:sleighCompile
Compiling ./data/languages/eBPF.slaspec:

1 languages successfully compiled
```

2022-12-19 13:54 UTC, jobermayr commented
Thanks. On my system also `Ghidra/Processors/eBPF/data/languages/eBPF.sla` changes on building:
https://github.com/jobermayr/ghidra-staging/commit/a5533d6

2022-12-19 16:04 UTC, GhidorahRex commented
We don't want to check in .sla files. They should be built at compile time.

2023-01-03 17:46 UTC, Nalen98 commented
> @Nalen98 Do you have a binary sample I could test the analyzers with?

I used this repository for testing purposes:
https://github.com/vbpf/ebpf-samples/tree/master/cilium

2023-01-24 14:49 UTC, GhidorahRex commented
I noticed that the .slaspec is just there to include `endian=little`, but nothing else. There seems to be support for big-endian variants of this. We don't necessarily need to include it currently, but if there's plans to include it later we should consider renaming `eBPF.slaspec` to `eBPF_le.slaspec`?

2023-01-25 15:29 UTC, Nalen98 commented
> I noticed that the .slaspec is just there to include `endian=little`, but nothing else. There seems to be support for big-endian variants of this. We don't necessarily need to include it currently, but if there's plans to include it later we should consider renaming `eBPF.slaspec` to `eBPF_le.slaspec`?

Thanks for the nice tip.
Recent actions:
* removed intermediate merges with the master branch, because it interferes with pull request management. Now it's a single commit to keep it clean.

* `eBPF.slaspec` renamed to `eBPF_le.slaspec` (including changes to `certification.manifest` and `eBPF.ldefs`).

2023-03-19 22:40 UTC, Nalen98 commented
Hello!

Any progress on reviewing this pull request? Can I help you?

2023-03-27 15:39 UTC, GhidorahRex commented
A couple small issues I noticed:
eBPF.dwarf and eBPF.sinc both contain carriage returns. I think git is expecting them to be the unix endings instead of windows.
eBPF_ElfRelocationHandler method relocate should have `RelocationResult` as the return type. Look at arm relocation handler as an example here.

2023-04-09 21:25 UTC, Nalen98 commented
@GhidorahRex, I've made a few corrections in accordance with your last remarks (press "Compare" to review the differences). These include:
* CRLF -> LF for `eBPF.dwarf` and `eBPF.sinc`
* `relocate#eBPF_ElfRelocationHandler` returns `RelocationResult` object
* `eBPF_ElfRelocationConstants.java` added to improve convenience and visibility when processing eBPF relocations

2023-04-10 13:47 UTC, GhidorahRex commented
> 

Thanks @Nalen98 !

2023-05-02 11:22 UTC, merged

2025-05-02 16:44 UTC, ghidra1 commented
@Nalen98 I realize you may this contribution a few years back, but by any chance do you recall why you specifically skipped relocation processing of debug related sections?

2025-05-06 12:28 UTC, Nalen98 commented
Hi @ghidra1 !

The issue is that if we don't filter out debug-related sections in the `eBPF_ElfRelocationHandler` class and apply relocations as-is, an exception will be thrown when loading any eBPF file that includes a debug section. Here's an example of such an exception observed in a real case:

```
ERROR (DWARFAnalyzer) Error during DWARFAnalyzer import:  ghidra.app.util.bin.format.dwarf.line.DWARFLineException: Unknown extended instruction: Unknown DWARF Value: 0x0
	at ghidra.app.util.bin.format.dwarf.line.DWARFLineProgramExecutor.executeExtended(DWARFLineProgramExecutor.java:180)
	at ghidra.app.util.bin.format.dwarf.line.DWARFLineProgramExecutor.stepInstr(DWARFLineProgramExecutor.java:111)
	at ghidra.app.util.bin.format.dwarf.line.DWARFLineProgramExecutor.step(DWARFLineProgramExecutor.java:97)
	at ghidra.app.util.bin.format.dwarf.line.DWARFLineProgramExecutor.nextRow(DWARFLineProgramExecutor.java:72)
	at ghidra.app.util.bin.format.dwarf.line.DWARFLineProgramExecutor.allRows(DWARFLineProgramExecutor.java:84)
	at ghidra.app.util.bin.format.dwarf.line.DWARFLine.getAllSourceFileAddrInfo(DWARFLine.java:280)
	at ghidra.app.util.bin.format.dwarf.DWARFImporter.addSourceLineInfo(DWARFImporter.java:219)
	at ghidra.app.util.bin.format.dwarf.DWARFImporter.performImport(DWARFImporter.java:411)
	at ghidra.app.plugin.core.analysis.DWARFAnalyzer.added(DWARFAnalyzer.java:104)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:37)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:24)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:660)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:760)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:639)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:604)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:55)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:33)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:351)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

As seen, `DWARFLineProgramExecutor` fails to process an instruction after the relocation, resulting in an error popup shown to the user.

Despite this, reverse engineering of the project can still be continued.

2025-05-21 14:59 UTC, ghidra1 commented
It would appear that the relocation processing differs for debug sections from what was implemented in the relocation handler.  The implementations and constraints seem very odd.  May I ask what documentation or code was used as a basis for the relocation processing logic?

2025-06-03 12:26 UTC, Nalen98 commented
The relocation processing logic for eBPF was created 6 years ago based on the official documentation "BPF LLVM Relocations":
https://www.kernel.org/doc/html/latest/bpf/llvm_reloc.html#different-relocation-types

This is reflected in the file `eBPF_ElfRelocationConstants.java`, which specifies the main types of relocations and their calculations. In `eBPF_ElfRelocationHandler.java`, the R_BPF_64_64 (ld_imm64 instructions) and R_BPF_64_32 (call instructions) relocations are handled in the overridden method `eBPF_ElfRelocationHandler#relocate`.