Make proper Arrays.toString() calls instead of .toString, which is im…
NationalSecurityAgency/ghidra pull request #4419
Opened 2022-07-06 23:23 UTC by GameCubeGBA

…proper for arrays

2023-04-13 13:06 UTC, ryanmkurtz requested changes

2023-04-13 13:06 UTC, ryanmkurtz commented on Ghidra/Features/PDB/src/main/java/ghidra/app/util/pdb/pdbapplicator/PdbAddressManager.java
> +			String name = Arrays.toString(symbol.getPath());
This look sketchy...it would need to be tested.

2023-06-25 16:00 UTC, GameCubeGBA commented
@ryanmkurtz Fixed!

2023-06-27 12:03 UTC, ryanmkurtz approved these changes

2023-06-27 12:12 UTC, closed without merging