V850: Added Extended Floating Point Instructions
NationalSecurityAgency/ghidra pull request #4481
Opened 2022-07-30 01:53 UTC by pjsoberoi

Added fmaf.s, fmsf.s, fnmaf.s fnmfs.s instructions. Closes issue https://github.com/NationalSecurityAgency/ghidra/issues/4453.

2022-07-30 01:54 UTC, pjsoberoi commented
@GhidorahRex: I added the fmsf.s and fnmaf.s as requested.

2022-07-30 04:39 UTC, ryanmkurtz commented
I see you marked that this PR closes #4453, but that ticket is already closed.  Should it be reopened?

2022-07-30 04:50 UTC, pjsoberoi commented
@ryanmkurtz, no need to reopen the ticket. User implemented the fix locally and closed the ticket. This is pushing the fix to Ghidra for other users.

2022-08-07 20:22 UTC, incognitojam requested changes

2022-08-07 20:22 UTC, incognitojam commented on Ghidra/Processors/V850/data/languages/Instructions/Float.sinc
> +
There's an extra blank line here

2022-08-07 21:14 UTC, pjsoberoi commented on Ghidra/Processors/V850/data/languages/Instructions/Float.sinc
> +
Removed

2022-08-22 11:38 UTC, esaulenka commented
Just for your information. Several year ago I did [another sleigh specification](https://github.com/esaulenka/ghidra_v850) for V850.
I am already added these instructions (I think, it is a latest V850 variant, RH850). I am don't have any real binaries for modern Renesas-es, but some users have spoken well about my implementation.

2022-10-08 03:06 UTC, pjsoberoi commented
@esaulenka : Any interested in contributing RH850 to Ghidra?

2023-01-10 16:53 UTC, closed without merging