golang support 1.21+
NationalSecurityAgency/ghidra pull request #6072
Opened 2023-12-31 14:59 UTC by astrelsky

I haven't actually tested go 1.22 yet since it hasn't been released. I did confirm that this works for 1.21.

2024-01-02 17:06 UTC, dev747368 commented
> I completely forgot about the "trim trailing whitespace" option. If it is too much I will try to work up the motivation to fix it.

When your PR is pulled in, our process will stomp on your whitespace changes in the license header comment block and put the whitespace back.

It will be a bit noisy in the commit for no good purpose.

2024-01-03 15:44 UTC, dev747368 requested changes

2024-01-03 17:21 UTC, astrelsky commented on Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/golang/rtti/types/GoUncommonType.java
> +	@FieldMapping(fieldName = {"pkgpath_nameOff", "PkgPath"})
Oh something else happened there. I thought it was originally that at the time. I'm not sure where the _nameoff came from.

2024-01-03 22:18 UTC, astrelsky commented on Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/golang/rtti/GoRttiMapper.java
> +		registerStructures(GOLANG_STRUCTMAPPED_CLASSES);
Looks like I forgot to remove this as well

2024-01-03 22:29 UTC, astrelsky commented on Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/golang/rtti/types/GoUncommonType.java
> +	@FieldMapping(fieldName = {"pkgpath_nameOff", "PkgPath"})
I figured out what happened here. After revising how I had previously done the changes I inadvertently copied the Java field's name thinking that's what the value had been.

2024-01-03 22:41 UTC, astrelsky commented
Ok it should be cleaner now and I fixed the problems.

However, since I like to live dangerously, I'm not even bothering to rebuild Ghidra 😝

2024-01-11 01:11 UTC, closed without merging