Update/docs
NationalSecurityAgency/ghidra pull request #6681
Opened 2024-06-30 13:39 UTC by h4ck3r-04

Added Documentation to the Annotation Validator.

2024-07-01 15:08 UTC, nsadeveloper789 requested changes
Thanks for adding these docs. This validator was a bit of an experiment, but Gradle does apply it when building Ghidra, so I suppose it should be documented. That said, please limit your changes to docs, since that's the title of the PR. Your formatter is not configured with our provided settings, and it's mangled our code in some places.

2024-07-01 15:08 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/ValidationContext.java
> -		DB_ANNOTATED_OBJECT_ELEM =
Unintended code formatting?

2024-07-01 15:08 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/ValidationContext.java
> -		}
Incorrect code formatting.

2024-07-01 15:08 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/ValidationContext.java
> -//		return typeUtils.isSameType(fieldType, type);
This is okay.

2024-07-01 16:09 UTC, h4ck3r-04 commented on .gitignore
> +
The change has been removed.

2024-07-01 16:11 UTC, h4ck3r-04 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/AbstractDBAnnotationValidator.java
> -				"@%s can only be applied to fields in a class", annotType.getSimpleName()), field);
Reverted the code to initial format.

2024-07-01 16:12 UTC, h4ck3r-04 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/AccessSpec.java
> +	/**
Removed the documentation for the private constructor.

2024-07-01 16:12 UTC, h4ck3r-04 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/ValidationContext.java
> -		DB_ANNOTATED_OBJECT_ELEM =
Reverted to the old code formatting

2024-07-01 16:13 UTC, h4ck3r-04 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/ValidationContext.java
> -		}
Fixed

2024-07-01 17:49 UTC, nsadeveloper789 requested changes
Thanks for reverting the code formatting. I don't mean to be annoying, but you missed a few spots. I've commented on a few and provided (I hope clearer) examples.

2024-07-01 17:49 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/DBAnnotatedFieldValidator.java
> +	 * Constructs a new {@code DBAnnotatedFieldValidator} with the specified validation context and field element.
"Construct" (no s)

2024-07-01 17:49 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/AccessSpec.java
> + * The {@code AccessSpec} enum represents different levels of access specifiers
"An enum to represent ..."

2024-07-01 17:49 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/AbstractDBAnnotationValidator.java
> +/**
Not sure I was clear enough here. I'll use this as an example (and I'll do another example below).

```java
/**
 * An abstract class for validation annotations on {@link DBAnotatedObject}.
 * 
 * <p>
 * Performs validation checks on annotated fields and their enclosing types.
 */
```

2024-07-01 17:49 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/DBAnnotatedColumnValidator.java
> +	/**
Another example where I'd like to see details separated from the brief:

```java
/**
 * Validate the annotated column field.
 * 
 * <p>
 * It performs the following checks to ensure the field meets the requirements for a database column:
 * <ul>
 * <li>...</li>
 * ...
 * </ul>
 */

2024-07-01 17:49 UTC, nsadeveloper789 commented on Ghidra/Debug/AnnotationValidator/src/main/java/ghidra/util/database/annotproc/DBAnnotatedFieldValidator.java
> +	 * Returns the default codec type element for the specified Java type.
"Return" (no s)

2024-07-02 12:32 UTC, nsadeveloper789 approved these changes
Awesome. Thanks for putting up with my pedantry in the javadocs. There are a few tweaks left, but it's pretty much just me running my doc formatter, so I can do that on our end.

2024-07-05 09:59 UTC, closed without merging