68HC05: Fix #7064 - incorrect handling of X-indexed JMP and JSR
NationalSecurityAgency/ghidra pull request #7065
Opened 2024-10-16 23:11 UTC by philpem

Fix for https://github.com/NationalSecurityAgency/ghidra/issues/7064 (incorrect handling of X-indexed JMP and JSR)

2024-10-18 10:46 UTC, byt3n33dl3 reviewed
JMP and JSR Code Review

2024-10-29 09:36 UTC, byt3n33dl3 requested changes
# Format / `Master`

```java
maybe back to "[ADDRI]" ?
```

2024-10-29 10:25 UTC, philpem commented
> # Format / `Master`
> 
> ```java
> maybe back to "[ADDRI]" ?
> ```

How do you expect changing the code back to the broken code, to fix the bug?

2024-10-29 19:32 UTC, philpem commented
> This doesn't fix the issue for the HC05/HC08/HCS08. The issue is that the subconstructor is exporting an address, so the `goto [ADDRI];` tries to de-reference the address, whereas `goto ADDRI` tries to go to the unique varnode `U500:1`. The solution is to change the subconstructor to export the value, rather than the address. But the subconstructors `oprx8_8_X`, `oprx16_8_X`, and `comma_X` are also used in `OP1` which _should_ export the address.
> 
> So this is what I came up with, and it seems to work well, leaving the brackets in `ADDRI`. I imagine the same changes would be needed for the 6805:
> 
> ```
> @if defined(HC05)
> oprx8_8_X:		imm8,X   is imm8 & X   { address:2 = zext(X) + imm8;   export  address; }
> oprx16_8_X:		imm16,X  is imm16 & X  { address:2 = zext(X) + imm16;  export  address; }
> comma_X:		","X     is X		   { address:2 = zext(X);          export  address; }
> @endif
> 
> @if defined(HCS08) || defined(HC08)
> oprx8_8_X:		imm8,X   is imm8 & X   { address:2 = HIX + imm8;       export address; }
> oprx16_8_X:		imm16,X  is imm16 & X  { address:2 = HIX + imm16;      export address; }
> comma_X:		","X     is X		   { address:2 = HIX;              export address; }
> @endif
> ```
> 
> and
> 
> ```
> OP1: iopr8i		is op4_6=2; iopr8i       { export iopr8i; }
> OP1: opr8a_8	is op4_6=3; opr8a_8      { export opr8a_8; }
> OP1: opr16a_8	is op4_6=4; opr16a_8     { export opr16a_8; }
> OP1: oprx16_8_X	is op4_6=5; oprx16_8_X   { export *:1 oprx16_8_X; }
> OP1: oprx8_8_X	is op4_6=6; oprx8_8_X    { export *:1 oprx8_8_X; }
> OP1: comma_X	is op4_6=7 & comma_X     { export *:1 comma_X; }
> ```



> This doesn't fix the issue for the HC05/HC08/HCS08. The issue is that the subconstructor is exporting an address, so the `goto [ADDRI];` tries to de-reference the address, whereas `goto ADDRI` tries to go to the unique varnode `U500:1`. The solution is to change the subconstructor to export the value, rather than the address. But the subconstructors `oprx8_8_X`, `oprx16_8_X`, and `comma_X` are also used in `OP1` which _should_ export the address.
> 
> So this is what I came up with, and it seems to work well, leaving the brackets in `ADDRI`. I imagine the same changes would be needed for the 6805:
> 
> ```
> @if defined(HC05)
> oprx8_8_X:		imm8,X   is imm8 & X   { address:2 = zext(X) + imm8;   export  address; }
> oprx16_8_X:		imm16,X  is imm16 & X  { address:2 = zext(X) + imm16;  export  address; }
> comma_X:		","X     is X		   { address:2 = zext(X);          export  address; }
> @endif
> 
> @if defined(HCS08) || defined(HC08)
> oprx8_8_X:		imm8,X   is imm8 & X   { address:2 = HIX + imm8;       export address; }
> oprx16_8_X:		imm16,X  is imm16 & X  { address:2 = HIX + imm16;      export address; }
> comma_X:		","X     is X		   { address:2 = HIX;              export address; }
> @endif
> ```
> 
> and
> 
> ```
> OP1: iopr8i		is op4_6=2; iopr8i       { export iopr8i; }
> OP1: opr8a_8	is op4_6=3; opr8a_8      { export opr8a_8; }
> OP1: opr16a_8	is op4_6=4; opr16a_8     { export opr16a_8; }
> OP1: oprx16_8_X	is op4_6=5; oprx16_8_X   { export *:1 oprx16_8_X; }
> OP1: oprx8_8_X	is op4_6=6; oprx8_8_X    { export *:1 oprx8_8_X; }
> OP1: comma_X	is op4_6=7 & comma_X     { export *:1 comma_X; }
> ```

Yep. I think this is the correct fix - it seems to work for me too, so I've pulled it into my branch.

I've applied the same fix to the 6805 SLASPEC too -- this also had a bug where the non-offset indexed syntax would be incorrect -- it would show as `LDA X` instead of `LDA ,X`.

2025-07-29 13:32 UTC, merged